### ISSUE TITLE
Reference to connect_1 in nginx config

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect-cli#30]
[nginz/conf.d/upstream.conf line 2](https://github.com/anvilresearch/connect-cli/blob/master/templates/nginx/conf.d/upstream.conf#L2) makes reference to `connect_1` for a server name.  The docker-compose yaml only makes a server called `connect`.  This caused an nginx failure when I tried to connect via nginx.

I am using my draft Windows script (see #29) so it is possible this is a difference between how my script works and how docker-compose works.

Should this _1 be there?  If not I can provide a PR as part of my work on Windows support to remove it.

**Comment by adalinesimonian** [comment]
It should be `connect` for it to work with container-linking.

Actually, what interests me is that this file doesn't seem to be in use anymore, yet it is still there. We are using `proxy_pass` directives in `default.conf` which point directly at the `connect` hostname. This may explain why this hasn't been caught (otherwise it would have been breaking connectivity for everyone.

Relevant lines in default.conf: [53](https://github.com/anvilresearch/connect-cli/blob/master/templates/nginx/conf.d/default.conf#L53), [68](https://github.com/anvilresearch/connect-cli/blob/master/templates/nginx/conf.d/default.conf#L68)

**Comment by adalinesimonian** [comment]
This brings up a good point: what should we do with `upstream.conf` - toss it?

**Comment by msamblanet** [comment]
It was actually causing a failure for me (which was the only reason I found it).  The pool might not actually be referenced but it is loaded due to [nginx.conf line 32](https://github.com/anvilresearch/connect-cli/blob/master/templates/nginx/nginx.conf#L32)

If it is not in use, then I'd suggest removing the file.  Only other sensible option would be to actually use the pool for the proxy config so that people can easily configure more servers.

**Comment by adalinesimonian** [comment]
Gah, you know what, this is one of those mornings where I haven't had enough coffee. I forgot that in nginx, `http://name_of_upstream_directive` actually will point to `upstream name_of_upstream_directive { ...`

If I haven't said anything plain silly again, the fix should be renaming connect_1 to connect. I'll test this locally to see if it causes any issues on GNU/Linux.

**Comment by adalinesimonian** [comment]
Tested the fix locally, no issues, everything worked a-OK. @msamblanet, would you mind throwing up a PR with the change so that we can review it? Would love to give you credit for finding this.

**Comment by christiansmith** [comment]
Some background on this file. Upstream is a separate file because we want to be able to generate it. The purpose is to add new containers running Connect to the load balancer as we scale out. 

`connect_1` is a reference to an /etc/hosts entry in the container that's created by Docker. We're telling docker to do that with the "link" property in `docker-compose.yaml`.

Here's the documentation on how Docker touches /etc/hosts: https://docs.docker.com/userguide/dockerlinks/#updating-the-etc-hosts-file

It may be that we need to reflect and determine the host OS and even check whether the project will be using Docker Compose, Kubernetes, etc, in order to generate the correct initial values in `upstream.conf`.

**Comment by adalinesimonian** [comment]
@christiansmith The linking system creates an /etc/hosts entry for `connect_1`, yes, but it also, and more consistently, creates an /etc/hosts entry for `connect`. If this wasn't the case, our Redis configuration would not work, because it points to `redis`, not `redis_1`.

**Comment by christiansmith** [comment]
We really need to get this stuff into documentation.

**Comment by adalinesimonian** [comment]
@christiansmith Agreed. In the meantime, though, I think @msamblanet is on the money here with the correction to `upstream.conf`, though the reasons may be different.

**Comment by christiansmith** [comment]
Sure, let's go ahead and merge that PR.

**Comment by adalinesimonian** [comment]
Fixed by #36
